# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # Define the available controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster


    ocs2_quadruped_controller:
      type: ocs2_quadruped_controller/Ocs2QuadrupedController

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"
    # imu noise parameters
    static_covariance_angular_velocity:
      - 0.0004  
      - 0.0
      - 0.0
      - 0.0
      - 0.0004  
      - 0.0
      - 0.0
      - 0.0
      - 0.0004  
    static_covariance_linear_acceleration:
      - 0.0012    
      - 0.0
      - 0.0
      - 0.0
      - 0.0012    
      - 0.0
      - 0.0
      - 0.0
      - 0.0012   
    static_covariance_orientation:
      - 0.0012       
      - 0.0
      - 0.0
      - 0.0
      - 0.0012
      - 0.0
      - 0.0
      - 0.0
      - 0.0012

ocs2_quadruped_controller:
  ros__parameters:
    update_rate: 500  # Hz
    robot_pkg: "cyberdog_description"
    default_kd: 1.25
    default_kp: 30.0
    feet_force_threshold: 3.0
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint

    command_interfaces:
      - effort
      - position
      - velocity
      - kp
      - kd

    state_interfaces:
      - effort
      - position
      - velocity

    feet:
      - FL_foot
      - FR_foot
      - RL_foot
      - RR_foot
    
    base_name: "base"
    


    imu_name: "imu_sensor"

    imu_interfaces:
      - orientation.w
      - orientation.x
      - orientation.y
      - orientation.z
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z
    

    static_covariance_angular_velocity:
      - 0.0004  
      - 0.0
      - 0.0
      - 0.0
      - 0.0004  
      - 0.0
      - 0.0
      - 0.0
      - 0.0004  
    static_covariance_linear_acceleration:
      - 0.0012    
      - 0.0
      - 0.0
      - 0.0
      - 0.0012    
      - 0.0
      - 0.0
      - 0.0
      - 0.0012   
    static_covariance_orientation:
      - 0.0012       
      - 0.0
      - 0.0
      - 0.0
      - 0.0012
      - 0.0
      - 0.0
      - 0.0
      - 0.0012

      
    foot_force_name: "foot_force"
    foot_force_interfaces:
      - FL_foot_force
      - RL_foot_force
      - FR_foot_force
      - RR_foot_force


